- hosts: all
  remote_user: "{{ ansible_system_user }}"
  vars_files:
    - group_vars/all.yml

  roles:
    - { role: elasticsearch_install }
    - { role: kibana_install }
    - { role: filebeat_install }
    - { role: zookeeper_install }
    - { role: kafka_install }
    - { role: logstash_install }
