- name: Copy kibana yum repo file
  copy:
    src=kibana-6.6.1-x86_64.rpm
    dest=/usr/local/kibana-6.6.1-x86_64.rpm
    owner=root
    group=root
    mode=0644
  become: true

- name: Install kibana rpms
  yum:
    name: /usr/local/kibana-6.6.1-x86_64.rpm
    state: present
  become: true

- name: Generate kibana configuration template
  template:
    src=kibana.yml.j2
    dest=/etc/kibana/kibana.yml
    owner=root
    group=root
    mode=0644
  become: true

- name: Setup kibana service
  service: name=kibana state=started enabled=true
  become: true
