---
- name: copy filebeat.rpm package
  copy: 
    src=filebeat-6.6.1-x86_64.rpm
    dest=/usr/local/filebeat-6.6.1-x86_64.rpm
    owner=root
    group=root
    mode=0644
  become: true


- name: install filebeat
  shell: rpm -ivh /usr/local/filebeat-6.6.1-x86_64.rpm

- name: Generate filebeat configuration template
  template:
    src=filebeat.yml.j2
    dest=/etc/filebeat/filebeat.yml
    owner=root
    group=root
    mode=0644
  become: true

- name: Start filebeat service
  service:
    name: filebeat
    state: started
    enabled: true
  ignore_errors: true
  become: true

- name: Setup filebeat service
  service: name=filebeat state=started enabled=true
  become: true
